# Generated by Django 4.2.30 on 2026-04-26 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nombre del Local"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(default="Chiclayo", max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "payment_phone",
                    models.CharField(
                        help_text="Celular para recibir Yape/Plin", max_length=15
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="complexes/"),
                ),
                ("has_parking", models.BooleanField(default=False)),
                ("has_showers", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complexes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Deporte"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Clase de FontAwesome (ej: fas fa-futbol)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Cancha 1 - Techada", max_length=100
                    ),
                ),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("5x5", "Fútbol 5"),
                            ("6x6", "Fútbol 6"),
                            ("7x7", "Fútbol 7"),
                            ("8x8", "Fútbol 8"),
                            ("11x11", "Fútbol 11"),
                            ("voley", "Voley standard"),
                            ("multi", "Multiusos"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price_per_hour", models.DecimalField(decimal_places=2, max_digits=7)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "complex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courts",
                        to="inventory.complex",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.sport",
                    ),
                ),
            ],
        ),
    ]
